config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'create_new_potter' }
  root :to => 'home#index'
  
  get "works/studio_ceramics" => "works#studio_ceramics", :as => :get_studio_ceramics
  get "works/domestic_ware" => "works#domestic_ware", :as => :get_domestic_ware
  get "works/in_situ" => "works#in_situ", :as => :get_in_situ
  
  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]
  
  resources :abouts
  resources :works
  resources :contacts
  resources :domesticwares do
    post :update_row_order, on: :collection
  end
  resources :studioceramics
  resources :insitus
  resources :cms
  

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "ed_hamilton@live.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/domesticware.rb
class Domesticware < ActiveRecord::Base
  
  include RankedModel
  ranks :row_order
  
  if Rails.env.development?
      has_attached_file :image, IMAGE_PAPERCLIP_STORAGE_OPTS
    else
      has_attached_file :image,
      :convert_options => { :all => '-quality 92' }, 
      styles: {main: '1200x'},
      :storage => :s3,
      :s3_credentials => {
      :access_key_id => ENV['S3_KEY'],
      :secret_access_key => ENV['S3_SECRET'] },
      :url => ':s3_alias_url',
      :s3_host_alias => 'd3sk2yopf63gjr.cloudfront.net', 
      :bucket => 'david-garland',
      :path => "domesticwares/images/:id_partition/:style/:filename"
    end

    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
    
end

app/models/insitu.rb
class Insitu < ActiveRecord::Base
  
  if Rails.env.development?
      has_attached_file :image, IMAGE_PAPERCLIP_STORAGE_OPTS
    else
      has_attached_file :image,
      :convert_options => { :all => '-quality 92' }, 
      styles: {main: '1200x'},
      :storage => :s3,
      :s3_credentials => {
      :access_key_id => ENV['S3_KEY'],
      :secret_access_key => ENV['S3_SECRET'] },
      :url => ':s3_alias_url',
      :s3_host_alias => 'd3sk2yopf63gjr.cloudfront.net', 
      :bucket => 'david-garland',
      :path => "insitus/images/:id_partition/:style/:filename"
    end

    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  
end

app/models/studioceramic.rb
class Studioceramic < ActiveRecord::Base
  
  if Rails.env.development?
      has_attached_file :image, IMAGE_PAPERCLIP_STORAGE_OPTS
    else
      has_attached_file :image,
      :convert_options => { :all => '-quality 92' }, 
      styles: {main: '1200x'},
      :storage => :s3,
      :s3_credentials => {
      :access_key_id => ENV['S3_KEY'],
      :secret_access_key => ENV['S3_SECRET'] },
      :url => ':s3_alias_url',
      :s3_host_alias => 'd3sk2yopf63gjr.cloudfront.net', 
      :bucket => 'david-garland',
      :path => "studioceramics/images/:id_partition/:style/:filename"
    end

    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  
  def index
    
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def define_models
    @domesticwares = Domesticware.all
    @domesticwaresdisplay = Domesticware.order("id ASC")
    @domesticware = Domesticware.first
    @studioceramics = Studioceramic.all
    @studioceramicsdisplay = Studioceramic.order("id ASC")
    @studioceramic = Studioceramic.first
    @insitus = Insitu.all
    @insitusdisplay = Insitu.order("id ASC")
    @insitu = Insitu.first
  end
end

app/controllers/cms_controller.rb
class CmsController < ApplicationController
  before_action :authenticate_user!

  
  def index
    define_models
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/domesticwares_controller.rb
class DomesticwaresController < ApplicationController
  before_action :authenticate_user!
  
  def new
    @domesticware = Domesticware.new
  end

  def create
    @domesticware = Domesticware.create(domesticware_params)
    respond_to do |format|
      format.html { redirect_to get_domestic_ware_path }
    end
  end

  def edit
    @domesticware = Domesticware.find(params[:id])
  end

  def update   
    @domesticware = Domesticware.find(params[:id])
    if @domesticware.update_attributes(domesticware_params)
      respond_to do |format|
       format.html { redirect_to cms_path }
       format.json { render :json => @domesticware }
      end
    else
      respond_to do |format|
        format.html { render :action  => :edit } # edit.html.erb
        format.json { render :nothing =>  true }
      end
    end
  end

  def destroy
    @domesticware = Domesticware.find(params[:id])
    @domesticware.destroy
    respond_to do |format|
      format.html { redirect_to cms_path }
    end
  end
  
  def update_row_order
    @domesticware = Domesticware.find(domesticware_params[:domesticware_id])
    @domesticware.row_order_position = domesticware_params[:row_order_position]
    @domesticware.save
    render nothing: true # this is a POST action, updates sent via AJAX, no view rendered
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_domesticware
    @domesticware = Domesticware.find(params[:id])
  end
  
  def domesticware_params
    params.require(:domesticware).permit(:domesticware_id, :description1, :description2, :image, :row_order_position)
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    
  end
  
end

app/controllers/insitus_controller.rb
class InsitusController < ApplicationController
  before_action :authenticate_user!
  
  def new
    @insitu = Insitu.new
  end

  def create
    @insitu = Insitu.create(insitu_params)
    respond_to do |format|
      format.html { redirect_to get_in_situ_path }
    end
  end

  def edit
    @insitu = Insitu.find(params[:id])
  end

  def update   
    @insitu = Insitu.find(params[:id])
    if @insitu.update_attributes(insitu_params)
      respond_to do |format|
       format.html { redirect_to cms_path }
       format.json { render :json => @insitu }
      end
    else
      respond_to do |format|
        format.html { render :action  => :edit } # edit.html.erb
        format.json { render :nothing =>  true }
      end
    end
  end

  def destroy
    @insitu = Insitu.find(params[:id])
    @insitu.destroy
    respond_to do |format|
      format.html { redirect_to cms_path }
    end
  end

  private
  
  def insitu_params
    params.require(:insitu).permit(:description1, :description2, :image)
  end
  
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  
  def studio_ceramics
    define_models
  end
  
  def domestic_ware
    define_models
  end
  
  def in_situ
    define_models
  end
  
  def show
    define_models
  end
  
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cms_helper.rb
module CmsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/domesticwares_helper.rb
module DomesticwaresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/insitus_helper.rb
module InsitusHelper
end

app/helpers/studioceramics_helper.rb
module StudioceramicsHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/abouts/index.html.erb
<div class="marginTop">
	<div class="col-md-7 clearSpace aboutPad justify">
		Born in England in 1941, David Garland grew up in New Zealand. In 1961 he returned and trained at the London College of Printing. Later, he taught there, and at the Bath Academy of Art, Corsham, as a senior lecturer.<br/><br/>
	
		He was also working as an artist. His first one-man exhibition of paintings was at the Drian Galleries in 1963.<br/><br/>
	
		in 1972 he was taught to make pots by the potter Jonathan Atkinson, and set up a small pottery in Oxford. IN 1975 he moved with his family to the Gloucestershire Cotswolds, where he built painting and pottery studios and a large wood-fired kiln.<br/><br/>
	
		At present he makes slipware, painted with oxides - cobalt, manganese, copper and iron, fired in an electric kiln. He sells mainly from the studio. and commissions from interior designers and private clients.
		<br/><br/><br/>
		<iframe src="https://player.vimeo.com/video/183839436" width="640" height="360" frameborder="0" 
		webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
		<br/><h4>Bibliography</h4><br/>
		<table>
			<tr class="spaceUnder">
				<td height="28" width="60" valign="top">2003</td>
				<td height="28" valign="top">British Studio Ceramics: Paul Rice, published by Crowood Press</td>
			</tr>
			<tr class="spaceUnder">
				<td height="28" width="60" valign="top">1989</td>
				<td height="28" valign="top">A Dictionary of British Studio Potters: Pat Carter, published by Scolar Press</td>
			</tr>
			<tr class="spaceUnder">
				<td height="28" width="60" valign="top">1987</td>
				<td height="28" valign="top">The New Ceramics: Trends and Traditions: Peter Dormer, published by Thames and Hudson</td>
			</tr>
		</table><br/>
		<div class="item">
	    	<%= image_tag('about.jpg') %>
	    </div>
		<br/><h4>Articles</h4><br/>
		<table>
			<tr class="spaceUnder">
				<td height="28" width="60" valign="top">2003</td>
				<td height="28" valign="top">British Studio Ceramics: Paul Rice, published by Crowood Press</td>
			</tr>
			<tr class="spaceUnder">
				<td height="28" width="60" valign="top">1989</td>
				<td height="28" valign="top">A Dictionary of British Studio Potters: Pat Carter, published by Scolar Press</td>
			</tr>
			<tr class="spaceUnder">
				<td height="28" width="60" valign="top">1987</td>
				<td height="28" valign="top">The New Ceramics: Trends and Traditions: Peter Dormer, published by Thames and Hudson</td>
			</tr>
		</table>
		<table>
			<tr class="spaceUnder">
				<td height="28" width="60" valign="top">2006</td>
				<td height="28" valign="top">Ceramic Review: Timothy Wilcox</td>
			</tr>
			<tr class="spaceUnder">
				<td height="28" width="60" valign="top">1992</td>
				<td height="28" valign="top">Crafts: Review Timothy Wilcox</td>
			</tr>
			<tr class="spaceUnder">
				<td height="28" width="60" valign="top">1990</td>
				<td height="28" valign="top">Crafts: Review Emmanual Cooper</td>
			</tr>
			<tr class="spaceUnder">
				<td height="28" width="60" valign="top">1988</td>
				<td height="28" valign="top">Contemporary British Crafts, Japan.<br/> 
				Ceramics Monthly, USA</td>
			</tr>	
			<tr class="spaceUnder">
				<td height="28" width="60" valign="top">1987</td>
				<td height="28" valign="top">Country Life: Leslie Geddes-Brown.  Crafts: Tanya Harrod.  British Vogue: Joanna Bell</td>
			</tr>
			<tr class="spaceUnder">
				<td height="28" width="60" valign="top">1984</td>
				<td height="28" valign="top">Arts Review: Fred Ross.  Crafts: Pamela Johnson.<br/>
				Crafts: Alison Britten</td>
			</tr>
		</table>
		<br/><h4>Video and film</h4><br/>
		<table>
			<tr class="spaceUnder">
				<td height="28" width="60" valign="top">1993</td>
				<td height="28" valign="top">Channel Four Television: For Love or Money Series</td>
			</tr>
			<tr class="spaceUnder">
				<td height="28" width="60" valign="top">1987</td>
				<td height="28" valign="top">Crafts Council Feature: Painter in Clay</td>
			</tr>
		</table><br/><br/>
	</div>
	<div class="col-md-5 clearSpace">
		<div class="item">
	      <%= image_tag('DG3.jpg') %>
	    </div>
	</div>
	<br/><br/>
	<div class="col-md-5 clearSpace">
		<br/><h4>Selected Solo Shows</h4><br/>
		<table>
			<tr class="spaceUnder">
				<td height="28" width="60" valign="top">2006</td>
				<td height="28" valign="top">David Garland: Ceramics<br/>
				<em>Galerie Besson, London</em></td>
			</tr>
			<tr class="spaceUnder">
				<td height="28" width="60" valign="top">2000</td>
				<td height="28" valign="top">David Garland: Ceramics<br/>
				<em>Kate Ganz USA, New York</em></td>
			</tr>
			<tr class="spaceUnder">
				<td height="28" width="60" valign="top">1992</td>
				<td height="28" valign="top">David Garland: Paintings and Pottery<br/>
				<em>The Charleston Gallery, Sussex</em></td>
			</tr>
			<tr class="spaceUnder">
				<td height="28" width="60" valign="top">1990</td>
				<td height="28" valign="top">David Garland: Paintings, Tempera, Gouaches &amp; Ceramics<br/>
				<em>Redfern Gallery, London</em></td>
			</tr>
			<tr class="spaceUnder">
				<td height="28" width="60" valign="top">1989</td>
				<td height="28" valign="top">David Garland: Works on paper<br/>
				<em>Oxford Gallery, Oxford</em></td>
			</tr>
			<tr class="spaceUnder">
				<td height="28" width="60" valign="top">1987</td>
				<td height="28" valign="top">David Garland: PotteryCrafts<br/>
				<em>Council Gallery, London and tour of UK</em></td>
			</tr>
			<tr class="spaceUnder">
				<td height="28" width="60" valign="top">1984</td>
				<td height="28" valign="top">David Garland: Paintings and Pottery<br/>
				<em>Cirencester Workshops, Cirencester, UK</em></td>
			</tr>
			<tr class="spaceUnder">
				<td height="28" width="60" valign="top">1984</td>
				<td height="28" valign="top">David Garland: Paintings<br/>
				<em>Oxford Gallery, Oxford</em></td>
			</tr>
			<tr class="spaceUnder">
				<td height="28" width="60" valign="top">1983</td>
				<td height="28" valign="top">David Garland: Pottery<br/>
				<em>Crafts Council at ICA, London</em></td>
			</tr>
		</table>
		<br/><h4>Selected Group Shows</h4><br/>
		<table>
			<tr class="spaceUnder">
				<td height="28" width="60" valign="top">2005</td>
				<td height="28" valign="top">Functional Form Now: British Domestic Ceramics <br/>
				<em>Galerie Besson, London</em></td>
			</tr>
			<tr class="spaceUnder">
				<td height="28" width="60" valign="top">2001</td>
				<td height="28" valign="top">Recent Work by Gallery Artists<br/>
				<em>Kate Ganz USA, New York</em></td>
			</tr>
			<tr class="spaceUnder">
				<td height="28" width="60" valign="top">1991</td>
				<td height="28" valign="top">Selection from a Private Collection<br/>
				<em>Galerie Besson, London</em></td>
			</tr>
			<tr class="spaceUnder">
				<td height="28" width="60" valign="top">1991</td>
				<td height="28" valign="top">Beyond the Dovetail<br/>
				<em>Crafts Council travelling exhibition</em></td>
			</tr>
			<tr class="spaceUnder">
				<td height="28" width="60" valign="top">1991</td>
				<td height="28" valign="top">Colours of the earth—20th Century British Ceramics<br/>
				<em>British Council travelling exhibition, India</em></td>
			</tr>
			<tr class="spaceUnder">
				<td height="28" width="60" valign="top">1988</td>
				<td height="28" valign="top">Contemporary British Crafts<br/>
				<em>Kyoto and Tokyo</em></td>
			</tr>
			<tr class="spaceUnder">
				<td height="28" width="60" valign="top">1988</td>
				<td height="28" valign="top">Sotheby’s Decorative Arts Award Exhibition<br/>
				<em>London</em></td>
			</tr>
			<tr class="spaceUnder">
				<td height="28" width="60" valign="top">1987</td>
				<td height="28" valign="top">Vessel<br/>
				<em>Serpentine Gallery, London</em></td>
			</tr>
			<tr class="spaceUnder">
				<td height="28" width="60" valign="top">1987</td>
				<td height="28" valign="top">Domestic Pottery<br/>
				<em>Contemporary Applied Arts, London</em></td>
			</tr>
			<tr class="spaceUnder">
				<td height="28" width="60" valign="top">1986</td>
				<td height="28" valign="top">International Art Fair<br/>
				<em>Chicago, USA</em></td>
			</tr>
			<tr class="spaceUnder">
				<td height="28" width="60" valign="top">1984</td>
				<td height="28" valign="top">New Spirit of Omega<br/>
				<em>Victoria and Albert Museum, London</em></td>
			</tr>
			<tr class="spaceUnder">
				<td height="28" width="60" valign="top">1984</td>
				<td height="28" valign="top">British Ceramics<br/>
				<em>Fremantle Arts Centre, Australia</em></td>
			</tr>
			<tr class="spaceUnder">
				<td height="28" width="60" valign="top">1984</td>
				<td height="28" valign="top">Tableware: New Domestic Pottery<br/>
				<em>Crafts Council Gallery, London and tour of UK</em></td>
			</tr>
		</table>
		<br/><h4>Works held in public collections</h4><br/>
		<p>Victoria and Albert Museum, British Crafts Council, Bradford City Art Gallery UK, Cleveland Art Gallery UK, Paisley Museum and Art Gallery UK</p><br/>
		<h4>Links</h4>
		<a href="http://www.belgravestives.co.uk/" target="_blank">Belgrave, St. Ives</a>
		<br/><br/><br/>
	</div>
</div>

app/views/cms/index.html.erb
<div class="col-md-12">
	<h2>Domestic Ware</h2><br/>
	<table class="table table-bordered table-striped">
		<thead>
	   		<tr>
	     		<th>ID</th>
	     		<th>Image</th>
	     		<th>Description</th>
				<th>Dimensions</th>
				<th></th>
	   		</tr>
	 	</thead>
	 	<tbody>
	   		<% @domesticwares.each do |dw| %>
				<tr data-item-id=<%= "#{dw.id}" %> class="item">
	    		<tr>
					<td width="7%"><%= dw.id %></td>
					<td class="thumbTiny" width="7%"><%= image_tag(dw.image, class: "thumb") %></td>
					<td width="38%"><%= dw.description1 %></td>
					<td width="38%"><%= dw.description2 %></td>
					<td width="10%">
						<%= link_to 'Edit', edit_domesticware_path(dw) %>
						<%= link_to 'Delete', dw, method: :delete, data: {confirm: "Are you sure you want to delete this record?"} %>
					</td>
	     		</tr>
	   		<% end %>
	 	</tbody>
	</table>
	<h2>Studio Ceramics</h2><br/>
	<table class="table table-bordered table-striped">
		<thead>
	   		<tr>
	     		<th>ID</th>
	     		<th>Image</th>
	     		<th>Description</th>
				<th>Dimensions</th>
				<th></th>
	   		</tr>
	 	</thead>
	 	<tbody>
	   		<% @studioceramics.each do |sc| %>
				<tr data-item-id=<%= "#{sc.id}" %> class="item">
	    		<tr>
					<td width="7%"><%= sc.id %></td>
					<td class="thumbTiny" width="7%"><%= image_tag(sc.image, class: "thumb") %></td>
					<td width="38%"><%= sc.description1 %></td>
					<td width="38%"><%= sc.description2 %></td>
					<td width="10%">
						<%= link_to 'Edit', edit_studioceramic_path(sc) %>
						<%= link_to 'Delete', sc, method: :delete, data: {confirm: "Are you sure you want to delete this record?"} %>
					</td>
	     		</tr>
	   		<% end %>
	 	</tbody>
	</table>
	<h2>In Situ</h2><br/>
	<table class="table table-bordered table-striped">
		<thead>
	   		<tr>
	     		<th>ID</th>
	     		<th>Image</th>
				<th></th>
	   		</tr>
	 	</thead>
	 	<tbody>
	   		<% @insitus.each do |is| %>
				<tr data-item-id=<%= "#{is.id}" %> class="item">
	    		<tr>
					<td width="7%"><%= is.id %></td>
					<td class="thumbTiny" width="7%"><%= image_tag(is.image, class: "thumb") %></td>
					<td width="10%">
						<%= link_to 'Edit', edit_insitu_path(is) %>
						<%= link_to 'Delete', is, method: :delete, data: {confirm: "Are you sure you want to delete this record?"} %>
					</td>
	     		</tr>
	   		<% end %>
	 	</tbody>
	</table>
</div>

app/views/home/index.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1" class=""></li>
    <li data-target="#carousel-example-generic" data-slide-to="2" class=""></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="../assets/DG1.jpg" alt="First slide" data-holder-rendered="true">
    </div>
    <div class="item">
      <img src="../assets/DG2.jpg" alt="Second slide" data-holder-rendered="true">
    </div>
  </div>
  <a class="left carousel-control" href="http://getbootstrap.com/examples/theme/#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="http://getbootstrap.com/examples/theme/#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/works/domestic_ware.html.erb
<div class="marginTop">
	<div class="col-md-8 clearSpace aboutPad2 largeImage">
		<div class="item thumbnail" id="panel">
		  	<img id="largeImage" src="<%= @domesticware.image %>" data-holder-rendered="true"><br/>
			<div id="description">
				<%= @domesticware.description1 %><br/>
				<%= @domesticware.description2 %>
			</div>
		</div>
	</div>
	<div class="col-md-4 clearSpace" id="thumbs">
		<% @domesticwaresdisplay.each do |dw| %>
			<div class="thumbnail col-md-3">
				<%= image_tag(dw.image, :alt => "#{dw.description1} <br/> #{dw.description2}", lazy: true, class: "lazy") %>
				<div class="number"><%= dw.id %></div>
			</div>
		<% end %>
		<% if user_signed_in? %>
			<div class="thumbnail col-md-3 end">
				<%= link_to(image_tag('add.png'), new_domesticware_path) %>
			</div>
		<% end %>
	</div>
	<div class="col-md-8">&nbsp;</div>
	<div class="col-md-4 end"><h2>Domestic Ware</h2></div>
</div>

app/views/works/in_situ.html.erb
<div class="marginTop">
	<div class="col-md-8 clearSpace aboutPad2 largeImage">
		<div class="item thumbnail" id="panel">
		  	<img id="largeImage" src="<%= @insitu.image %>" data-holder-rendered="true"><br/>
		</div>
	</div>
	<div class="col-md-4 clearSpace" id="thumbs">
		<% @insitusdisplay.each do |is| %>
			<div class="thumbnail col-md-3">
				<%= image_tag(is.image, lazy: true, class: "lazy") %>
			</div>
		<% end %>
		<% if user_signed_in? %>
			<div class="thumbnail col-md-3">
				<%= link_to(image_tag('add.png'), new_insitu_path) %>
			</div>
		<% end %>
	</div>
	<div class="col-md-8">&nbsp;</div>
	<div class="col-md-4 end2"><h2>In Situ</h2></div>
</div>

app/views/works/studio_ceramics.html.erb
<div class="marginTop">
	<div class="col-md-8 clearSpace aboutPad2 largeImage">
		<div class="item thumbnail" id="panel">
		  	<img id="largeImage" src="<%= @studioceramic.image %>" data-holder-rendered="true"><br/>
			<div id="description">
				<%= @studioceramic.description1 %><br/>
				<%= @studioceramic.description2 %>
			</div>
		</div>
	</div>
	<div class="col-md-4 clearSpace" id="thumbs">
		<% @studioceramicsdisplay.each do |sc| %>
			<div class="thumbnail col-md-3">
				<%= image_tag(sc.image, :alt => "#{sc.description1} <br/> #{sc.description2}", lazy: true, class: "lazy") %>
				<div class="number"><%= sc.id %></div>
			</div>
		<% end %>
		<% if user_signed_in? %>
			<div class="thumbnail col-md-3">
				<%= link_to(image_tag('add.png'), new_studioceramic_path) %>
			</div>
		<% end %>
	</div>
	<div class="col-md-8">&nbsp;</div>
	<div class="col-md-4 end"><h2>Studio Ceramics</h2></div>
</div>