config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'create_new_potter' }
  root :to => 'home#index'
  
  get "works/studio_ceramics" => "works#studio_ceramics", :as => :get_studio_ceramics
  get "works/domestic_ware" => "works#domestic_ware", :as => :get_domestic_ware
  get "works/in_situ" => "works#in_situ", :as => :get_in_situ
  
  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]
  
  resources :abouts
  resources :works
  resources :contacts
  resources :domesticwares do
    post :update_row_order, on: :collection
  end
  resources :studioceramics
  resources :insitus
  resources :cms
  

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "ed_hamilton@live.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/domesticware.rb
class Domesticware < ActiveRecord::Base
  
  include RankedModel
  ranks :row_order
  
  if Rails.env.development?
      has_attached_file :image, IMAGE_PAPERCLIP_STORAGE_OPTS
    else
      has_attached_file :image,
      :convert_options => { :all => '-quality 92' }, 
      styles: {main: '1200x'},
      :storage => :s3,
      :s3_credentials => {
      :access_key_id => ENV['S3_KEY'],
      :secret_access_key => ENV['S3_SECRET'] },
      :url => ':s3_alias_url',
      :s3_host_alias => 'd3sk2yopf63gjr.cloudfront.net', 
      :bucket => 'david-garland',
      :path => "domesticwares/images/:id_partition/:style/:filename"
    end

    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
    
end

app/models/insitu.rb
class Insitu < ActiveRecord::Base
  
  if Rails.env.development?
      has_attached_file :image, IMAGE_PAPERCLIP_STORAGE_OPTS
    else
      has_attached_file :image,
      :convert_options => { :all => '-quality 92' }, 
      styles: {main: '1200x'},
      :storage => :s3,
      :s3_credentials => {
      :access_key_id => ENV['S3_KEY'],
      :secret_access_key => ENV['S3_SECRET'] },
      :url => ':s3_alias_url',
      :s3_host_alias => 'd3sk2yopf63gjr.cloudfront.net', 
      :bucket => 'david-garland',
      :path => "insitus/images/:id_partition/:style/:filename"
    end

    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  
end

app/models/studioceramic.rb
class Studioceramic < ActiveRecord::Base
  
  if Rails.env.development?
      has_attached_file :image, IMAGE_PAPERCLIP_STORAGE_OPTS
    else
      has_attached_file :image,
      :convert_options => { :all => '-quality 92' }, 
      styles: {main: '1200x'},
      :storage => :s3,
      :s3_credentials => {
      :access_key_id => ENV['S3_KEY'],
      :secret_access_key => ENV['S3_SECRET'] },
      :url => ':s3_alias_url',
      :s3_host_alias => 'd3sk2yopf63gjr.cloudfront.net', 
      :bucket => 'david-garland',
      :path => "studioceramics/images/:id_partition/:style/:filename"
    end

    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  
  def index
    
  end
  
end

app/controllers/cms_controller.rb
class CmsController < ApplicationController
  before_action :authenticate_user!

  
  def index
    define_models
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    
  end
  
end

app/controllers/insitus_controller.rb
class InsitusController < ApplicationController
  before_action :authenticate_user!
  
  def new
    @insitu = Insitu.new
  end

  def create
    @insitu = Insitu.create(insitu_params)
    respond_to do |format|
      format.html { redirect_to get_in_situ_path }
    end
  end

  def edit
    @insitu = Insitu.find(params[:id])
  end

  def update   
    @insitu = Insitu.find(params[:id])
    if @insitu.update_attributes(insitu_params)
      respond_to do |format|
       format.html { redirect_to cms_path }
       format.json { render :json => @insitu }
      end
    else
      respond_to do |format|
        format.html { render :action  => :edit } # edit.html.erb
        format.json { render :nothing =>  true }
      end
    end
  end

  def destroy
    @insitu = Insitu.find(params[:id])
    @insitu.destroy
    respond_to do |format|
      format.html { redirect_to cms_path }
    end
  end

  private
  
  def insitu_params
    params.require(:insitu).permit(:description1, :description2, :image)
  end
  
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  
  def studio_ceramics
    define_models
  end
  
  def domestic_ware
    define_models
  end
  
  def in_situ
    define_models
  end
  
  def show
    define_models
  end
  
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cms_helper.rb
module CmsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/domesticwares_helper.rb
module DomesticwaresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/insitus_helper.rb
module InsitusHelper
end

app/helpers/studioceramics_helper.rb
module StudioceramicsHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/layouts/_header.html.erb
<div class="page-header">
 	<div class="container-fluid">
		<h1><%= link_to 'David Garland', root_path %></h1>
      	<ul class="nav navbar-nav" id="menu">
        	<li class="active"><%= link_to 'About', abouts_path %></li>
        	<li class="dropdown">
          		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" 
				aria-expanded="false">Work <span class="caret"></span></a>
          		<ul class="dropdown-menu">
            		<li><%= link_to 'Studio Ceramics', get_studio_ceramics_path %></li>
            		<li><%= link_to 'Domestic Ware', get_domestic_ware_path %></li>
					<li><%= link_to 'In Situ', get_in_situ_path %></li>
          		</ul>
        	</li>
			<li><%= link_to 'Contact', contacts_path %></li>
      	</ul>
    </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  	<title>David Garland | Potter</title>
  	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	
  	<%= csrf_meta_tags %>
</head>

<% if controller_name == "home" %>
	<body class="homeImage" data-ride=""><div class="bgImage1"><%= image_tag('sides.png') %></div>
		<div class="bgImage2"><%= image_tag('shapes.png') %></div>
		<div class="container theme-showcase" role="main">
			<%= render 'layouts/header' %>
			<%= yield %>
		</div>
		<% if user_signed_in? %>
			<div class="userInfo">
				<div>{ Logged in as <strong><%= current_user.email %></strong> }</div>
				<%= link_to 'Edit', edit_user_registration_path, class: "clearFixer" %> | 
				<%= link_to 'Logout', destroy_user_session_path, :method => :delete, class: "clearFixer" %> |
				<%= link_to 'CMS', cms_path %></div>
			</div>
		<% end %>
	</body>
<% else %>
	<body>
		<div class="bgImage1"><%= image_tag('sides.png') %></div>
		<div class="bgImage2"><%= image_tag('shapes.png') %></div>
		<div class="container theme-showcase" role="main">
			<%= render 'layouts/header' %>
			<%= yield %>
		</div>
		<% if user_signed_in? %>
			<div class="userInfo">
				<div>{ Logged in as <strong><%= current_user.email %></strong> }</div>
				<%= link_to 'Edit', edit_user_registration_path, class: "clearFixer" %> | 
				<%= link_to 'Logout', destroy_user_session_path, :method => :delete, class: "clearFixer" %> |
				<%= link_to 'CMS', cms_path %></div>
			</div>
		<% end %>
	</body>
<% end %>
</html>